[package]
name = "LasViewer"
version = "0.1.0"
authors = [""]

[dependencies]
las = "0.6"
gfx = "0.17"
glutin = "0.19"
gfx_window_glutin = "0.28"
cgmath = "0.16"
clap = "2.0"
log = "0.4"
env_logger = "0.5"
chrono = "0.4"